### ISSUE TITLE
LDI croaks when submitting to InfluxDB

### ISSUE THREAD

**Issue by amotl** [hiveeyes/luftdatenpumpe#4]
We just found that `luftdatenpumpe readings --network=ldi` currently croaks half-way by yielding:
```
2019-06-26 12:48:46,140 [luftdatenpumpe.commands             ] INFO   : Acquiring readings from network "ldi" with source "api"
2019-06-26 12:48:46,154 [luftdatenpumpe.commands             ] INFO   : Will publish data to ['influxdb://luftdatenpumpe@localhost/vmm']
2019-06-26 12:48:46,155 [luftdatenpumpe.engine               ] INFO   : Configuring data sink "influxdb://luftdatenpumpe@localhost/vmm" with domain "readings"
2019-06-26 12:48:46,587 [luftdatenpumpe.engine               ] INFO   : Emitting to target data sinks, this might take some time
2019-06-26 12:48:46,587 [luftdatenpumpe.source.luftdaten_info] INFO   : Requesting luftdaten.info live API at https://api.luftdaten.info/static/v1/data.json
2019-06-26 12:48:49,116 [luftdatenpumpe.source.luftdaten_info] INFO   : Timestamp of first record: 2019-06-26T10:38:52Z
Traceback (most recent call last):
  File "/usr/local/bin/luftdatenpumpe", line 10, in <module>
    sys.exit(run())
  File "/opt/luftdatenpumpe/lib/python3.6/site-packages/luftdatenpumpe/commands.py", line 161, in run
    run_engine(options)
  File "/opt/luftdatenpumpe/lib/python3.6/site-packages/luftdatenpumpe/commands.py", line 302, in run_engine
    engine.process(data)
  File "/opt/luftdatenpumpe/lib/python3.6/site-packages/luftdatenpumpe/engine.py", line 75, in process
    target.flush()
  File "/opt/luftdatenpumpe/lib/python3.6/site-packages/luftdatenpumpe/target/influxdb.py", line 135, in flush
    self.db.write_points(self.buffer)
  File "/opt/luftdatenpumpe/lib/python3.6/site-packages/influxdb/client.py", line 490, in write_points
    tags=tags, protocol=protocol)
  File "/opt/luftdatenpumpe/lib/python3.6/site-packages/influxdb/client.py", line 551, in _write_points
    protocol=protocol
  File "/opt/luftdatenpumpe/lib/python3.6/site-packages/influxdb/client.py", line 327, in write
    headers=headers
  File "/opt/luftdatenpumpe/lib/python3.6/site-packages/influxdb/client.py", line 286, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write: unable to parse 'ldi_readings,geohash=srxwdb8ny7j6,sensor_id=22673,station_id=11504  1561545544000000000': invalid field format\nunable to parse 'ldi_readings,geohash=srxwdb8ny7j6,sensor_id=22674,station_id=11504  1561545545000000000': invalid field format dropped=0"}
```

**Comment by amotl** [comment]
@wetterfrosch said:
> Looks like there are some values missing between the tags and the timestamp.

**Comment by amotl** [comment]
We haven't been able to reproduce this, apparently `station=11504` already has valid data again. However, we added some additional gracefulness with 276f2a27.
